# ボットのトークン (環境変数 $DISCORD_TOKEN で指定可)
token: ""

# 言語 (en, ja)
locale: ja

# 発信するチャンネル (複数指定可)
channels:
  - guild: "000000000000000000" # DiscordサーバーID
    channel: "000000000000000000" # DiscordチャンネルID
    message: "`%2$s`(`%3$s`,`%4$s`) left `%1$s`" # メッセージ